### ISSUE TITLE
Creating unit tests

### ISSUE THREAD

**Issue by raulpardo** [itu-square/privugger#10]
* We should create the infrastructure for unit testing. 
* Then we should add several unit tests checking the correctness of probability queries and privacy measures (#4).
  * The tests should take into account the analytical expected value and variance of the estimators.

**Comment by Pluttodk** [comment]
We need to agree upon which test to have. Currently I am considerering the following:

- Evaluation of Rasmus tool. To simply ensure type correction. Such that Normal (pymc3) gives a types of pm.dist.Normal. etc.
- Sampling with `k` gives us exactly `k` samples. 
- Ensuring that if we have two dist (a,b) and sample on a method that o is executed as [(a_0,b_0), ... ,(a_i,b_i)]
- Validate that mutual information gives the analytical solution (with a small margin for error).
- Perhaps a test to ensure that observation shift the distribution?

**Comment by raulpardo** [comment]
added in #22
