### ISSUE TITLE
Hide packages structure from the `import` declarations

### ISSUE THREAD

**Issue by raulpardo** [itu-square/privugger#29]
Currently, we need way too many imports to access the different packages in the library, e.g., data structures, distributions, etc. It would be better to have just one import with everything.

**Comment by RasmusCarl** [comment]
I believe I included this in the last PR, so you just need to write `from privugger.transformer import *` and then you get all the stuff.

**Comment by raulpardo** [comment]
> I believe I included this in the last PR, so you just need to write `from privugger.transformer import *` and then you get all the stuff.

This seems to work for some, but not all, functions. For instance, I cannot access the constructor `Dataset`. I think we should configure modules so that we simply write `import privugger as pv` and then use `pv` to call the corresponding function.

**Comment by raulpardo** [comment]
Fixed on #33
