### ISSUE TITLE
Running multiple times with pymc3 backend throws an error

### ISSUE THREAD

**Issue by raulpardo** [itu-square/privugger#52]
When running `infer` multiple times with the pymc3 backend we get an error. It seems to be related to re-defining the pymc3 model more than once.

**Comment by RasmusCarl** [comment]
I have tried to fix the issue with redefining the model by using the `del` keyword to explicitly remove the model object after running `infer`. I am not sure if this is the way to go

**Comment by raulpardo** [comment]
fixed

**Comment by raulpardo** [comment]
We re-open as it doesn't work with the newest modifications

**Comment by raulpardo** [comment]
Remember that this could have problems with concatenate

**Comment by raulpardo** [comment]
Fixed in #92

**Comment by raulpardo** [comment]
We have to reopen because it does not work for the tests

**Comment by raulpardo** [comment]
Fixed by @wasowski in #112
