### ISSUE TITLE
re variable not found

### ISSUE THREAD

**Issue by S3j5b0** [itu-square/privugger#82]
Hi, I was running the examples from the tutorial.
I got to this point:

```
trace   = pv.infer(program, 
                   cores=4,
                   draws=10_000,
                   method='pymc3')
```
This runs for a while but then fails with:
```
/python3.8/site-packages/privugger/data_structures/program.py", line 54, in add_observation
    vals = re.search(cons, constraints)
NameError: name 're' is not defined
```

I guessed that  it was probably regex missing, so I tried just adding it as a reference to that.
Then  I ran it again, to which I got:

```
python3.8/site-packages/privugger/data_structures/program.py", line 121, in inner
    pm.Normal(f"cons_{i}", distribution,        precision, observed=value)
NameError: name 'pm' is not defined
```

Could there be missing some imports? or am I maybe doing something wrong?

**Comment by S3j5b0** [comment]
I now also tried importing pymc3 as pm. It works now

**Comment by raulpardo** [comment]
Thanks for the feedack! Did you install privvuger using `pip`?

**Comment by S3j5b0** [comment]
Hi :) Yeah, or I don't know if it's relevant but I used pip3
